# BANSHAP INVESTMENT COMPANY LIMITED - Local Assets Setup
# =========================================================
# Run from PowerShell inside the project folder:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\setup_local_assets.ps1

$ErrorActionPreference = "SilentlyContinue"
$ProgressPreference    = "SilentlyContinue"

$fontsDir   = "assets\fonts"
$fontsCSS   = "assets\css\fonts.css"
$clientsDir = "assets\img\clients"

New-Item -ItemType Directory -Force -Path $fontsDir   | Out-Null
New-Item -ItemType Directory -Force -Path $clientsDir | Out-Null

$ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

function Download-File($url, $dest, $referer, $minBytes) {
    if ($minBytes -eq $null) { $minBytes = 200 }
    if ((Test-Path $dest) -and (Get-Item $dest).Length -gt $minBytes) {
        Write-Host "  [skip] $(Split-Path $dest -Leaf)"
        return $true
    }
    try {
        $headers = @{ "User-Agent" = $ua }
        if ($referer) { $headers["Referer"] = $referer }
        Invoke-WebRequest -Uri $url -Headers $headers -OutFile $dest -UseBasicParsing
        $size = (Get-Item $dest).Length
        if ($size -lt $minBytes) {
            Remove-Item $dest -Force
            Write-Host "  [fail] $(Split-Path $dest -Leaf) - too small ($size bytes)"
            return $false
        }
        $kb = [math]::Round($size / 1KB)
        Write-Host "  [ok]   $(Split-Path $dest -Leaf) - $kb KB"
        return $true
    } catch {
        Write-Host "  [fail] $(Split-Path $dest -Leaf) - $($_.Exception.Message)"
        return $false
    }
}

# ---- 1. Download Google Fonts -----------------------------------------------

Write-Host ""
Write-Host "============================================================"
Write-Host "Step 1: Downloading Google Fonts"
Write-Host "============================================================"

$fontRequests = @(
    @{ name="Poppins";   url="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" },
    @{ name="Inter";     url="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap" },
    @{ name="Outfit";    url="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" },
    @{ name="Open Sans"; url="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" },
    @{ name="Jost";      url="https://fonts.googleapis.com/css2?family=Jost:wght@300;400;500;600;700&display=swap" }
)

$faceBlocks = New-Object System.Collections.Generic.List[string]
$fontErrors = New-Object System.Collections.Generic.List[string]

foreach ($font in $fontRequests) {
    Write-Host ""
    Write-Host "  $($font.name):"
    try {
        $headers = @{ "User-Agent" = $ua }
        $resp = Invoke-WebRequest -Uri $font.url -Headers $headers -UseBasicParsing
        $css  = $resp.Content
    } catch {
        Write-Host "    [fail] Could not fetch CSS: $($_.Exception.Message)"
        $fontErrors.Add($font.name)
        continue
    }

    $blockMatches = [regex]::Matches($css, '@font-face\s*\{[^}]+\}', [System.Text.RegularExpressions.RegexOptions]::Singleline)
    $okCount = 0

    foreach ($block in $blockMatches) {
        $b = $block.Value

        $familyM = [regex]::Match($b, "font-family:\s*'([^']+)'")
        $styleM  = [regex]::Match($b, 'font-style:\s*(\w+)')
        $weightM = [regex]::Match($b, 'font-weight:\s*([\d]+)')
        $srcM    = [regex]::Match($b, "url\(([^)]+)\)\s*format\('woff2'\)")

        if (-not ($familyM.Success -and $weightM.Success -and $srcM.Success)) { continue }

        $family   = $familyM.Groups[1].Value -replace ' ', ''
        $style    = if ($styleM.Success) { $styleM.Groups[1].Value } else { "normal" }
        $weight   = $weightM.Groups[1].Value
        $woff2url = $srcM.Groups[1].Value.Trim("'`"")

        $filename = "$($family.ToLower())-$weight-$style.woff2"
        $dest     = Join-Path $fontsDir $filename

        if (Download-File $woff2url $dest $null 1000) {
            $unicodeM    = [regex]::Match($b, 'unicode-range:\s*([^;]+);')
            $unicodeLine = if ($unicodeM.Success) { "`n  unicode-range: $($unicodeM.Groups[1].Value);" } else { "" }

            $block_text = "@font-face {`n  font-family: '$($familyM.Groups[1].Value)';`n  font-style: $style;`n  font-weight: $weight;`n  font-display: swap;`n  src: url('../fonts/$filename') format('woff2');$unicodeLine`n}"
            $faceBlocks.Add($block_text)
            $okCount++
        }
    }
    Write-Host "    -> $okCount weights saved"
}

if ($faceBlocks.Count -gt 0) {
    $cssContent  = "/* Self-hosted Google Fonts - generated by setup_local_assets.ps1 */`r`n`r`n"
    $cssContent += $faceBlocks -join "`r`n`r`n"
    $cssContent += "`r`n"
    $cssPath = Join-Path (Get-Location) $fontsCSS
    [System.IO.File]::WriteAllText($cssPath, $cssContent, [System.Text.Encoding]::UTF8)
    Write-Host ""
    Write-Host "  OK: $fontsCSS written ($($faceBlocks.Count) font-face rules)"
} else {
    Write-Host ""
    Write-Host "  ERROR: No font faces collected - fonts.css not written"
}

# ---- 2. Download Client Logos -----------------------------------------------

Write-Host ""
Write-Host "============================================================"
Write-Host "Step 2: Checking Client Logos"
Write-Host "============================================================"
Write-Host ""

$logos = @(
    @{ file="crdb.svg";    url="https://crdbbank.co.tz/storage/app/media/images/logo.svg";  referer="https://crdbbank.co.tz/" },
    @{ file="nmb.png";     url="https://www.nmbbank.co.tz/images/nmb-white-logo.png";        referer="https://www.nmbbank.co.tz/" },
    @{ file="vodacom.png"; url="https://images.seeklogo.com/logo-png/21/1/vodacom-logo-png_seeklogo-215102.png"; referer="https://seeklogo.com/" },
    @{ file="azam.png";    url="https://images.seeklogo.com/logo-png/63/1/azam-logo-png_seeklogo-631037.png";    referer="https://seeklogo.com/" },
    @{ file="tanesco.png"; url="https://images.seeklogo.com/logo-png/31/1/tanesco-tanzania-electric-supply-company-limited-logo-png_seeklogo-311615.png"; referer="https://seeklogo.com/" },
    @{ file="tpa.png";     url="https://images.seeklogo.com/logo-png/56/1/tanzania-ports-authority-tpa-logo-png_seeklogo-569241.png"; referer="https://seeklogo.com/" }
)

$logoOk   = 0
$logoFail = New-Object System.Collections.Generic.List[object]

foreach ($logo in $logos) {
    $dest = Join-Path $clientsDir $logo.file
    if (Download-File $logo.url $dest $logo.referer 500) {
        $logoOk++
    } else {
        $logoFail.Add($logo)
    }
    Start-Sleep -Milliseconds 400
}

# ---- Summary ----------------------------------------------------------------

Write-Host ""
Write-Host "============================================================"
Write-Host "Summary"
Write-Host "============================================================"
Write-Host "  Fonts : $($faceBlocks.Count) font-face rules -> $fontsCSS"
Write-Host "  Logos : $logoOk/$($logos.Count) ready in $clientsDir"

if ($fontErrors.Count -gt 0) {
    Write-Host ""
    Write-Host "  Font errors: $($fontErrors -join ', ')"
}
if ($logoFail.Count -gt 0) {
    Write-Host ""
    Write-Host "  Logo failures - save these manually into $clientsDir :"
    foreach ($l in $logoFail) { Write-Host "    $($l.file.PadRight(15)) $($l.url)" }
}
if ($fontErrors.Count -eq 0 -and $logoFail.Count -eq 0) {
    Write-Host ""
    Write-Host "  All assets local - site is ready for fast loading!"
}
